### ISSUE TITLE
error 503

### ISSUE THREAD

**Issue by croccio** [iambluedev1/cfscrape-api#1]
(node:11250) UnhandledPromiseRejectionWarning: HTTPError: Response code 503 (Service Temporarily Unavailable)
    at stream.catch.then.data (/Users/antonioscardigno/Downloads/filminfoapi/cfscrape-api/node_modules/got/index.js:372:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:11250) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11250) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by iambluedev1** [comment]
Hi,

I have tested some websites under the cloudflare's protection, and it works. But, sometimes when you spam the raw's request an error 503 may occure. The solution is to wait arround 5seconds, to make the request (my repo cfscrape-java already do this).

Maybe, when an error occure, retry the failed's request.
